# **Implementation of forward and backward propagation from scratch for linear regression**

In [ ]:
!pip install numpy
!pip install pandas

In [ ]:
import numpy as np
import pandas as pd


ModuleNotFoundError: No module named 'pandas'

In [ ]:
df = pd.DataFrame([[8,8,4] , [7,9,5] , [6,10,6] , [5,12,7]] , columns = ['cgpa' , 'profile_score','lpa'])

In [ ]:
df.head()

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [11]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1,L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1] , layer_dims[l])) * 0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l] , 1))

    return parameters

In [13]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [15]:
def linear_forward(A_prev , W , b):
  Z = np.dot(W.T , A_prev)+b
  return Z

In [70]:
#forward prop
def L_layer_forward(X , parameters):
  A = X
  L = len(parameters) # 2 -> no of layers in the neural network

  for l in range(1 , L-1 ):
    A_prev = A
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]

    # print('A' + str(l-1)+ ": ", A_prev)
    # print('W' + str(l) + ": ",W1)
    # print('b' + str(l) + ": ",b1)
    # print("--"*20)

    A = linear_forward(A_prev , W1 , b1)
    # print('A' + str(l)+": ",A)
    # print("**"*20)

  return A , A_prev

In [50]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)   ## taking for the first student
y = df[['lpa']].values[0][0]

#parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat , A1 = L_layer_forward(X , parameters)

le 4
A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [51]:
y_hat =y_hat[0][0]

In [52]:
def update_parameters(parameters , y , y_hat , A1 , X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [53]:
update_parameters(parameters , y , y_hat , A1 , X)

In [54]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [55]:
#for 2nd student
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X, parameters)

le 4
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************


In [56]:
y_hat = y_hat[0][0]

In [57]:
update_parameters(parameters,y,y_hat,A1,X)

In [58]:
parameters

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [59]:
#for 3rd student
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X, parameters)

le 4
A0:  [[ 6]
 [10]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.83539945]
 [1.87200826]]
****************************************
A1:  [[1.83539945]
 [1.87200826]]
W2:  [[0.12712927]
 [0.12712927]]
b2:  [[0.13612818]]
----------------------------------------
A2:  [[0.6074482]]
****************************************


In [60]:
y_hat = y_hat[0][0]

In [61]:
update_parameters(parameters,y,y_hat,A1,X)

In [62]:
parameters

{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

In [63]:
#for 4th student
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X, parameters)

le 4
A0:  [[ 5]
 [12]]
W1:  [[0.12409711 0.13272353]
 [0.12412266 0.13276611]]
b1:  [[0.00355129]
 [0.00355555]]
----------------------------------------
A1:  [[2.11350869]
 [2.26036654]]
****************************************
A1:  [[2.11350869]
 [2.26036654]]
W2:  [[0.14692424]
 [0.14731907]]
b2:  [[0.15810417]]
----------------------------------------
A2:  [[0.80162493]]
****************************************


In [64]:
y_hat = y_hat[0][0]

In [65]:
update_parameters(parameters,y,y_hat,A1,X)

In [66]:
parameters

{'W1': array([[0.13482804, 0.15847776],
        [0.1349909 , 0.15884991]]),
 'b1': array([[0.00569748],
        [0.0057292 ]]),
 'W2': array([[0.17312488],
        [0.17534027]]),
 'b2': array([[0.18773702]])}

In [71]:
# epochs implementation

parameters = initialize_parameters([2,2,1])   #initilize weights and bias
epochs = 5

for i in range(epochs):
  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa' , 'profile_score']].values[j].reshape(2,1)
    y = df[['lpa']].values[j][0]

    #parameter initialization

    y_hat , A1 = L_layer_forward(X , parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters , y , y_hat , A1 , X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ' , i+1 , 'Loss - ', np.array(Loss).mean())

parameters


Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

# **Implementation using keras**

In [72]:
import numpy as np
import pandas as pd


In [73]:
df = pd.DataFrame([[8,8,4] , [7,9,5] , [6,10,6] , [5,12,7]] , columns = ['cgpa' , 'profile_score','lpa'])

In [77]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [78]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [80]:
model = Sequential()

In [81]:
model.add(Dense(2,activation = 'linear' , input_dim = 2))
model.add(Dense(1,activation = 'linear'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [82]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [84]:
model.get_weights()

[array([[ 0.10084081,  0.26135457],
        [-0.1680057 , -0.8695377 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.53858817],
        [ 0.67748797]], dtype=float32),
 array([0.], dtype=float32)]

In [85]:
new_weights = [np.array([[0.1 , 0.1],[0.1,0.1]] , dtype = np.float32) ,
               np.array([0.,0.], dtype = np.float32) ,
               np.array([[0.1],[0.1]],dtype = np.float32) ,
               np.array([0.],dtype = np.float32)]

In [87]:
model.set_weights(new_weights)

In [88]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [89]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = "mean_squared_error" , optimizer = optimizer)

In [90]:
model.fit(df.iloc[: , 0:-1].values , df['lpa'].values , epochs = 75 , verbose = 1 , batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 33.6870
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.1464 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.3488 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.0603 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.4036 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.8483 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.6178 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.3230 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.1259 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.4205 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1859 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 27.5629 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.3407 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.6639 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.6566 
Epoch 16/75
4/4 ━━━━